
services:


  # NGINX reverse proxy to hide all ports
  desa-nginx:
    image: nginx:alpine
    container_name: desa-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always
    depends_on:
      - desa-explorer
      - desa-pgadmin
      - desa-ows
    networks:
      - desa-network

  # OpenDataCube Explorer
  desa-explorer:
    image: opendatacube/explorer:latest
    container_name: explorer
    environment:
      DB_HOSTNAME: "${PGDB_HOSTNAME}"
      DB_USERNAME: "${PGDB_USERNAME}"
      DB_PASSWORD: "${PGDB_PASSWORD}"
      DB_DATABASE: "${PGDB_DATABASE}"
      DB_PORT: "5432"
      FLASK_ENV: deployment
      FLASK_APP: cubedash
      FLASK_DEBUG: 1
      CUBEDASH_DEFAULT_TIMEZONE: Australia/Darwin
    networks:
      - desa-network
    depends_on:
      - desa-postgres

  # JupyterHub service
  desa-terriamap:
    build: ./desa-terriamap
    image: terriamap  
    container_name: map
    networks:
      - desa-network
    expose:
      - "3001:3001"
    restart: unless-stopped
      
    

  # PostgreSQL database
  desa-postgres:
    container_name: desa-postgres
    image: postgis/postgis:16-3.4
    hostname: "${PGDB_HOSTNAME}"
    environment:
      POSTGRES_DB: "${PGDB_DATABASE}"
      POSTGRES_PASSWORD: "${PGDB_PASSWORD}"
      POSTGRES_USER: "${PGDB_USERNAME}"
    # Expose port only internally, not on host
    expose:
      - "5432"
    networks:
      - desa-network
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "postgres",
          "-q",
          "-d",
          "opendatacube",
          "-U",
          "opendatacube",
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PGAdmin interface
  desa-pgadmin:
    container_name: desa-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ingqambuza@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - desa-network
    depends_on:
      - desa-postgres

  # OWS service
  desa-ows:
    image: opendatacube/ows:1.8.0-rc1
    environment:
      DB_HOSTNAME: "${PGDB_HOSTNAME}"
      DB_USERNAME: "${PGDB_USERNAME}"
      DB_PASSWORD: "${PGDB_PASSWORD}"
      DB_DATABASE: "${PGDB_DATABASE}"
      DB_PORT: 5432
      AWS_DEFAULT_REGION: "${AWS_REGION}"
      AWS_NO_SIGN_REQUEST: "${AWS_NO_SIGN_REQUEST}"
      PYTHONPATH: /env/config
      DATACUBE_OWS_CFG: ows_refactored.dev_af_ows_root_cfg.ows_cfg
    networks:
      - desa-network
    depends_on:
      - desa-postgres
    volumes:
      - ./desa-ows/products:/products
      - ./desa-ows/services/ows_refactored:/env/config/ows_refactored/
      - ./desa-ows/services/inventory:/env/config/inventory/
      - ./desa-ows/output:/env/config/output/

networks:
  desa-network:
    driver: bridge

volumes:
  jupyterhub_data:
  postgres_data: