---
services:
  explorer:
    build:
      context: .
      args:
        ENVIRONMENT: deployment
    ports:
      - 80:8080
    environment:
      # - DB_HOSTNAME=host.docker.internal
      - DB_HOSTNAME=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
      - DB_PORT=5432
      - FLASK_ENV=development
      - FLASK_APP=cubedash
      - FLASK_DEBUG=1
      - CUBEDASH_DEFAULT_TIMEZONE=Australia/Darwin
      # - VIRTUAL_HOST=datacube.explorer
    depends_on:
      - postgres

  postgres:
    container_name: ODC-DB
    image: postgis/postgis:16-3.4
    hostname: postgres
    environment:
      - POSTGRES_DB=d
      - POSTGRES_PASSWORD=V2
      - POSTGRES_USER=
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-q", "-d", "opendatacube", "-U", "opendatacube"]
      timeout: 45s
      interval: 10s
      retries: 10
  pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ingqambuza@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"

  

  # Needed for testing HTTPS
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "5000:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #   depends_on:
  #     - explorer
