---

services:
  desa-explorer:
    build:
      context: ./datacube-explorer
    ports:
      - 80:8080
    environment:
      # - DB_HOSTNAME=host.docker.internal
      DB_HOSTNAME: "${DB_HOSTNAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${PGDB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_PORT: "5432"
      FLASK_ENV: deployment
      FLASK_APP: cubedash
      FLASK_DEBUG: 1
      CUBEDASH_DEFAULT_TIMEZONE: Australia/Darwin
      # - VIRTUAL_HOST=datacube.explorer
    depends_on:
      - desa-postgres

  desa-sandbox:
    build:
      context: ./dea-sandbox/docker
      args:
        - WITH_SUDO=yes
    environment:
      AWS_NO_SIGN_REQUEST: "true"
      AWS_DEFAULT_REGION: ap-southeast-2
      DATACUBE_DB_URL: postgresql://${DB_USERNAME}:${PGDB_PASSWORD}@${DB_HOSTNAME}/${DB_DATABASE}

    ports:
      - "9988:9988"
    restart: always
    volumes:
      - ./notebooks:/home/indiphile
  desa-maps:
    build:
      context: ./TerriaMap
    ports: 
      - "3001:3001"

  desa-postgres:
    container_name: desa-postgres
    image: postgis/postgis:16-3.4
    hostname: "${DB_HOSTNAME}"
    environment:
      POSTGRES_DB: "${PGDB_DATABASE}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "postgres",
          "-q",
          "-d",
          "opendatacube",
          "-U",
          "opendatacube",
        ]
      timeout: 45s
      interval: 10s
      retries: 10

  desa-pgadmin:
    container_name: desa-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ingqambuza@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
