version: "3.7"

services:
  postgres:
    image: kartoza/postgis:11.0-2.5
    environment:
      - POSTGRES_DB=datacube_sandbox_noncomm
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=datacube_sandbox_eo3_noncomm
    ports:
      - 5439:5432
    restart: always

  sandbox:
    environment:
      - DATACUBE_DB_URL=postgresql://datacube:password@localhost/datacube_user
